### PR TITLE
fixes TestIntegrationServerUpdateComponents intermittent failures

### LINKED ISSUE #105: An Update and select on an existing row returns zero rows intermittently.
A update and a subsequent select on an existing row returns zero rows.
                                                                                                                             
This issue at the time of writing seems to be in crdb, and some work needs to be done
for this to be tested outside of the serverservice context using the same sqlboiler adapter. 

I'm creating this ticket to track/compare notes. Its quite possible this could just be a non-issue
and turns out to be a crdb configuration/v21.1 issue, until its figured out, we'll add findings here. 

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
The issue shows up always in the first iteration - `test-0`,
and shows up in atleast 3 out of 5 attempts of the test execution.

The cause is that crdb intermittently returns no rows for the select
statement.

OS: macos
crdb server: v21.1


In the failed senario, the `count(*)` returns 1 row as expected, but the final select returns no rows, no `NumRows` in exec log.
```
I220713 07:17:45.721420 12485075 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:55636›,hostnossl,user=root] 1975 ={"Timestamp":1657696665718409000,"EventType":"query_execute","Statement":"‹UPDATE \"\".\"\".server_components SET name = $1, vendor = $2, model = $3, serial = $4, server_component_type_id = $5, server_id = $6, updated_at = $7 WHERE id = $8›","Tag":"UPDATE","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹''›","‹'test-0'›","‹'Left'›","‹'f940627a-8474-41c0-ab37-f4a810c97916'›","‹'84735c80-a711-4597-950e-1021b6376bc0'›","‹'2022-07-13 07:17:45.688831+00:00'›","‹'666a55ed-74ed-484a-aa62-705ec2524236'›"],"ExecMode":"exec","NumRows":1,"Age":3.1635,"TxnCounter":2}

I220713 07:17:46.752804 12485023 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:55634›,hostnossl,user=root] 1978 ={"Timestamp":1657696666748893500,"EventType":"query_execute","Statement":"‹SELECT count(*) FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3))›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-0'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":4.1912,"FullTableScan":true,"TxnCounter":50}

I220713 07:17:46.759494 12485023 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:55634›,hostnossl,user=root] 1979 ={"Timestamp":1657696666756782500,"EventType":"query_execute","Statement":"‹SELECT * FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3)) ORDER BY server_components.created_at DESC LIMIT 100›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-0'›","‹'Right'›"],"ExecMode":"exec","Age":2.8987,"FullTableScan":true,"TxnCounter":51}
```


In the successful senario, the `count(*)` and the select returns 1 row `"NumRows":1`
```
I220713 07:21:55.693586 12489922 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57888›,hostnossl,user=root] 3535 ={"Timestamp":1657696915690572800,"EventType":"query_execute","Statement":"‹UPDATE \"\".\"\".server_components SET name = $1, vendor = $2, model = $3, serial = $4, server_component_type_id = $5, server_id = $6, updated_at = $7 WHERE id = $8›","Tag":"UPDATE","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹''›","‹'test-0'›","‹'Right'›","‹'42d0fc33-e4c2-4e7c-8e55-911ca112ea71'›","‹'539d6c85-2344-4bbc-b62c-79ecc8f3ce2b'›","‹'2022-07-13 07:21:55.683093+00:00'›","‹'3314c271-acda-457a-961f-5e11480948b4'›"],"ExecMode":"exec","NumRows":1,"Age":3.1143,"TxnCounter":2}

I220713 07:21:55.715837 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3538 ={"Timestamp":1657696915713834500,"EventType":"query_execute","Statement":"‹SELECT count(*) FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3))›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-0'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":2.1364,"FullTableScan":true,"TxnCounter":50}

I220713 07:21:55.721582 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3539 ={"Timestamp":1657696915719081000,"EventType":"query_execute","Statement":"‹SELECT * FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3)) ORDER BY server_components.created_at DESC LIMIT 100›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-0'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":2.6206,"FullTableScan":true,"TxnCounter":51}
```

## fixes attempted
 - Run tests serially with `-p1`.
 - Run Update without the transaction block.
 - Add delay between Update and List(Select)




To reproduce this issue,
## setup the test db
```
make docker-up
make test-database
```

## export env variable to execute test manually
```
export SERVERSERVICE_DB_URI="host=localhost port=26257 user=root
sslmode=disable dbname=serverservice_test
```

## save reproducer as a test file
The test loop here updates a component model attribute
the loop is set to a high value to prevent the test from being cached,
assuming the user does not run the test for the 2000 iterations.

```
func TestLoopUpdate(t *testing.T) {
        s := serverTest(t)

    // this is here just to get a test auth token
        realClientTests(t, func(ctx context.Context, authToken string, respCode int, expectError bool) error {
                s.Client.SetToken(authToken)
                attrs, _, err := s.Client.GetComponents(ctx, uuid.MustParse(dbtools.FixtureNemo.ID), nil)
                if !expectError {
                        require.NoError(t, err)
                        assert.Len(t, attrs, 2)
                }

                return err
        })

    // list current servers
        servers, _, err := s.Client.List(context.Background(), nil)
        if err != nil {
                t.Fatal(err)
        }

    // the components for update
        componentSliceFixture := func() []serverservice.ServerComponent {
                s := serverservice.ServerComponentSlice{}

                for _, c := range servers[0].Components {
                        c := c
                        s = append(s, c)
                }

                return s
        }

    // component list query params
        params := &serverservice.ServerComponentListParams{
                Name:   "Normal Fin",
                Serial: "Right",
        }

        ctx, _ := context.WithCancel(context.Background())
        for i := 0; i <= 2000; i++ {
                components := componentSliceFixture()
        // update attribute for test
                components[0].Model = "test-" + strconv.Itoa(i)
                params.Model = components[0].Model

                fmt.Println(components[0].Model)

                //      update component
                _, err = s.Client.UpdateComponents(ctx, servers[0].UUID, components)
                assert.Nil(t, err)

                // list component updated
                got, _, err := s.Client.ListComponents(ctx, params)
                if err != nil {
                        t.Error(err)
                }

        // expect updated component to be returned
                assert.Len(t, got, 1)
                assert.Equal(t, components[0].Model, got[0].Model)
        }
}
```

enable debug mode in update method to dump sql query
```
func (r *Router) serverComponentUpdate(c *gin.Context) {
        boil.DebugMode = true
        defer func() { boil.DebugMode = false }()
```

run test
```
❯ /usr/local/bin/go test -timeout 30s -tags testtools -run ^TestLoopUpdate$ go.hollow.sh/serverservice/pkg/api/v1 -v
=== RUN   TestLoopUpdate
=== RUN   TestLoopUpdate/happy_path
=== RUN   TestLoopUpdate/invalid_auth_token
=== RUN   TestLoopUpdate/auth_token_with_no_scopes
=== RUN   TestLoopUpdate/fake_timeout
test-0
select * from "servers" where "id"=$1 and "deleted_at" is null
[65fd17a9-71f5-477f-8779-713101fbf14c]
select exists(select 1 from "server_components" where "id"=$1 limit 1)
41445f7c-e9b9-4678-bb78-927a8ab19cb1
UPDATE "server_components" SET "name"=$1,"vendor"=$2,"model"=$3,"serial"=$4,"server_component_type_id"=$5,"server_id"=$6,"updated_at"=$7 WHERE "id"=$8
[{Normal Fin true} { true} {test-0 true} {Left true} 2215fce6-7646-4053-89a8-67bae050d880 65fd17a9-71f5-477f-8779-713101fbf14c {2022-07-13 07:00:14.776816 +0000 UTC true} 41445f7c-e9b9-4678-bb78-927a8ab19cb1]
select exists(select 1 from "server_components" where "id"=$1 limit 1)
8fa91ee8-6a57-4d46-8697-ba9dee6802ec
UPDATE "server_components" SET "name"=$1,"vendor"=$2,"model"=$3,"serial"=$4,"server_component_type_id"=$5,"server_id"=$6,"updated_at"=$7 WHERE "id"=$8
[{Normal Fin true} { true} { true} {Right true} 2215fce6-7646-4053-89a8-67bae050d880 65fd17a9-71f5-477f-8779-713101fbf14c {2022-07-13 07:00:14.794443 +0000 UTC true} 8fa91ee8-6a57-4d46-8697-ba9dee6802ec]
=== CONT  TestLoopUpdate
    router_server_components_test.go:434:
                Error Trace:    router_server_components_test.go:434
                Error:          "[]" should have 1 item(s), but has 0
                Test:           TestLoopUpdate
--- FAIL: TestLoopUpdate (0.63s)
    --- PASS: TestLoopUpdate/happy_path (0.02s)
    --- PASS: TestLoopUpdate/invalid_auth_token (0.00s)
    --- PASS: TestLoopUpdate/auth_token_with_no_scopes (0.00s)
    --- PASS: TestLoopUpdate/fake_timeout (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
        panic: runtime error: index out of range [0] with length 0

goroutine 26 [running]:
testing.tRunner.func1.2({0x1a0eb80, 0xc0001284b0})
        /usr/local/Cellar/go/1.18.1/libexec/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
        /usr/local/Cellar/go/1.18.1/libexec/src/testing/testing.go:1392 +0x39f
panic({0x1a0eb80, 0xc0001284b0})
        /usr/local/Cellar/go/1.18.1/libexec/src/runtime/panic.go:838 +0x207
go.hollow.sh/serverservice/pkg/api/v1_test.TestLoopUpdate(0xc000421860)
        /Users/jrebello/go/src/github.com/joelrebel/hollow-serverservice/pkg/api/v1/router_server_components_test.go:435 +0x4c5
testing.tRunner(0xc000421860, 0x1ae5b90)
        /usr/local/Cellar/go/1.18.1/libexec/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
        /usr/local/Cellar/go/1.18.1/libexec/src/testing/testing.go:1486 +0x35f
FAIL    go.hollow.sh/serverservice/pkg/api/v1   1.366s
FAIL
```


enable cockroach auth logs, sql execution logs
```
/usr/local/bin/cockroach sql --url "postgresql://root@localhost:26257/?sslmode=disable"   --insecure


root@localhost:26257/serverservice_test> SET CLUSTER SETTING server.auth_log.sql_connections.enabled=true;
SET CLUSTER SETTING

root@localhost:26257/defaultdb> SET CLUSTER SETTING sql.trace.log_statement_execute=true;
SET CLUSTER SETTING
```


```
❯ docker exec -ti 53aa0952d219 tail -f cockroach-data/logs/cockroach-sql-auth.log

I220713 06:46:54.606706 12452550 4@util/log/event_log.go:32 ⋮
[n1,client=‹172.22.0.1:60216›] 34
={"Timestamp":1657694814606688500,"EventType":"client_connection_start","InstanceID":1,"Network":"tcp","RemoteAddress":"‹172.22.0.1:60216›"}
I220713 06:46:54.957601 12452617 4@util/log/event_log.go:32 ⋮
[n1,client=‹172.22.0.1:60218›] 35
={"Timestamp":1657694814957583600,"EventType":"client_connection_start","InstanceID":1,"Network":"tcp","RemoteAddress":"‹172.22.0.1:60218›"}
I220713 06:46:55.271442 12452617 4@util/log/event_log.go:32 ⋮
[n1,client=‹172.22.0.1:60218›,hostnossl] 36
={"Timestamp":1657694815271423200,"EventType":"client_connection_end","InstanceID":1,"Network":"tcp","RemoteAddress":"‹172.22.0.1:60218›","Duration":313839600}
I220713 06:46:55.272470 12452550 4@util/log/event_log.go:32 ⋮
[n1,client=‹172.22.0.1:60216›,hostnossl] 37
={"Timestamp":1657694815272446300,"EventType":"client_connection_end","InstanceID":1,"Network":"tcp","RemoteAddress":"‹172.22.0.1:60216›","Duration":665757800}
^C
```

A failed update, select
```
docker exec -ti 53aa0952d219 tail -n 0 -f cockroach-data/logs/cockroach-sql-exec.log | grep 'test-'

I220713 07:17:45.721420 12485075 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:55636›,hostnossl,user=root] 1975 ={"Timestamp":1657696665718409000,"EventType":"query_execute","Statement":"‹UPDATE \"\".\"\".server_components SET name = $1, vendor = $2, model = $3, serial = $4, server_component_type_id = $5, server_id = $6, updated_at = $7 WHERE id = $8›","Tag":"UPDATE","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹''›","‹'test-0'›","‹'Left'›","‹'f940627a-8474-41c0-ab37-f4a810c97916'›","‹'84735c80-a711-4597-950e-1021b6376bc0'›","‹'2022-07-13 07:17:45.688831+00:00'›","‹'666a55ed-74ed-484a-aa62-705ec2524236'›"],"ExecMode":"exec","NumRows":1,"Age":3.1635,"TxnCounter":2}
I220713 07:17:46.752804 12485023 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:55634›,hostnossl,user=root] 1978 ={"Timestamp":1657696666748893500,"EventType":"query_execute","Statement":"‹SELECT count(*) FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3))›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-0'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":4.1912,"FullTableScan":true,"TxnCounter":50}
I220713 07:17:46.759494 12485023 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:55634›,hostnossl,user=root] 1979 ={"Timestamp":1657696666756782500,"EventType":"query_execute","Statement":"‹SELECT * FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3)) ORDER BY server_components.created_at DESC LIMIT 100›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-0'›","‹'Right'›"],"ExecMode":"exec","Age":2.8987,"FullTableScan":true,"TxnCounter":51}
```


A successful update of 10 items
```
❯ docker exec -ti 53aa0952d219 tail -n 0 -f cockroach-data/logs/cockroach-sql-exec.log | grep 'test-'
I220713 07:21:55.693586 12489922 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57888›,hostnossl,user=root] 3535 ={"Timestamp":1657696915690572800,"EventType":"query_execute","Statement":"‹UPDATE \"\".\"\".server_components SET name = $1, vendor = $2, model = $3, serial = $4, server_component_type_id = $5, server_id = $6, updated_at = $7 WHERE id = $8›","Tag":"UPDATE","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹''›","‹'test-0'›","‹'Right'›","‹'42d0fc33-e4c2-4e7c-8e55-911ca112ea71'›","‹'539d6c85-2344-4bbc-b62c-79ecc8f3ce2b'›","‹'2022-07-13 07:21:55.683093+00:00'›","‹'3314c271-acda-457a-961f-5e11480948b4'›"],"ExecMode":"exec","NumRows":1,"Age":3.1143,"TxnCounter":2}
I220713 07:21:55.715837 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3538 ={"Timestamp":1657696915713834500,"EventType":"query_execute","Statement":"‹SELECT count(*) FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3))›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-0'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":2.1364,"FullTableScan":true,"TxnCounter":50}
I220713 07:21:55.721582 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3539 ={"Timestamp":1657696915719081000,"EventType":"query_execute","Statement":"‹SELECT * FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3)) ORDER BY server_components.created_at DESC LIMIT 100›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-0'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":2.6206,"FullTableScan":true,"TxnCounter":51}
I220713 07:21:55.752041 12489922 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57888›,hostnossl,user=root] 3545 ={"Timestamp":1657696915749553600,"EventType":"query_execute","Statement":"‹UPDATE \"\".\"\".server_components SET name = $1, vendor = $2, model = $3, serial = $4, server_component_type_id = $5, server_id = $6, updated_at = $7 WHERE id = $8›","Tag":"UPDATE","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹''›","‹'test-1'›","‹'Right'›","‹'42d0fc33-e4c2-4e7c-8e55-911ca112ea71'›","‹'539d6c85-2344-4bbc-b62c-79ecc8f3ce2b'›","‹'2022-07-13 07:21:55.742428+00:00'›","‹'3314c271-acda-457a-961f-5e11480948b4'›"],"ExecMode":"exec","NumRows":1,"Age":2.582,"TxnCounter":6}
I220713 07:21:55.774153 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3548 ={"Timestamp":1657696915771635300,"EventType":"query_execute","Statement":"‹SELECT count(*) FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3))›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-1'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":2.6623,"FullTableScan":true,"TxnCounter":57}
I220713 07:21:55.780711 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3549 ={"Timestamp":1657696915777957900,"EventType":"query_execute","Statement":"‹SELECT * FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3)) ORDER BY server_components.created_at DESC LIMIT 100›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-1'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":2.8461,"FullTableScan":true,"TxnCounter":58}
I220713 07:21:55.809979 12489922 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57888›,hostnossl,user=root] 3555 ={"Timestamp":1657696915807643200,"EventType":"query_execute","Statement":"‹UPDATE \"\".\"\".server_components SET name = $1, vendor = $2, model = $3, serial = $4, server_component_type_id = $5, server_id = $6, updated_at = $7 WHERE id = $8›","Tag":"UPDATE","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹''›","‹'test-2'›","‹'Right'›","‹'42d0fc33-e4c2-4e7c-8e55-911ca112ea71'›","‹'539d6c85-2344-4bbc-b62c-79ecc8f3ce2b'›","‹'2022-07-13 07:21:55.800696+00:00'›","‹'3314c271-acda-457a-961f-5e11480948b4'›"],"ExecMode":"exec","NumRows":1,"Age":2.431,"TxnCounter":10}
I220713 07:21:55.838839 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3558 ={"Timestamp":1657696915832586000,"EventType":"query_execute","Statement":"‹SELECT count(*) FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3))›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-2'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":6.2945,"FullTableScan":true,"TxnCounter":64}
I220713 07:21:55.845040 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3559 ={"Timestamp":1657696915842783100,"EventType":"query_execute","Statement":"‹SELECT * FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3)) ORDER BY server_components.created_at DESC LIMIT 100›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-2'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":2.3382,"FullTableScan":true,"TxnCounter":65}
I220713 07:21:55.882080 12489922 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57888›,hostnossl,user=root] 3565 ={"Timestamp":1657696915874378300,"EventType":"query_execute","Statement":"‹UPDATE \"\".\"\".server_components SET name = $1, vendor = $2, model = $3, serial = $4, server_component_type_id = $5, server_id = $6, updated_at = $7 WHERE id = $8›","Tag":"UPDATE","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹''›","‹'test-3'›","‹'Right'›","‹'42d0fc33-e4c2-4e7c-8e55-911ca112ea71'›","‹'539d6c85-2344-4bbc-b62c-79ecc8f3ce2b'›","‹'2022-07-13 07:21:55.86617+00:00'›","‹'3314c271-acda-457a-961f-5e11480948b4'›"],"ExecMode":"exec","NumRows":1,"Age":8.2332,"TxnCounter":14}
I220713 07:21:55.912631 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3568 ={"Timestamp":1657696915909733700,"EventType":"query_execute","Statement":"‹SELECT count(*) FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3))›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-3'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":2.973,"FullTableScan":true,"TxnCounter":71}
I220713 07:21:55.920684 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3569 ={"Timestamp":1657696915915975300,"EventType":"query_execute","Statement":"‹SELECT * FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3)) ORDER BY server_components.created_at DESC LIMIT 100›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-3'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":4.9702,"FullTableScan":true,"TxnCounter":72}
I220713 07:21:55.965015 12489922 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57888›,hostnossl,user=root] 3575 ={"Timestamp":1657696915959731000,"EventType":"query_execute","Statement":"‹UPDATE \"\".\"\".server_components SET name = $1, vendor = $2, model = $3, serial = $4, server_component_type_id = $5, server_id = $6, updated_at = $7 WHERE id = $8›","Tag":"UPDATE","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹''›","‹'test-4'›","‹'Right'›","‹'42d0fc33-e4c2-4e7c-8e55-911ca112ea71'›","‹'539d6c85-2344-4bbc-b62c-79ecc8f3ce2b'›","‹'2022-07-13 07:21:55.952113+00:00'›","‹'3314c271-acda-457a-961f-5e11480948b4'›"],"ExecMode":"exec","NumRows":1,"Age":5.4545,"TxnCounter":18}
I220713 07:21:55.994338 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3578 ={"Timestamp":1657696915992256800,"EventType":"query_execute","Statement":"‹SELECT count(*) FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3))›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-4'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":2.3437,"FullTableScan":true,"TxnCounter":78}
I220713 07:21:56.000914 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3579 ={"Timestamp":1657696915997730200,"EventType":"query_execute","Statement":"‹SELECT * FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3)) ORDER BY server_components.created_at DESC LIMIT 100›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-4'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":3.3589,"FullTableScan":true,"TxnCounter":79}
I220713 07:21:56.036841 12489922 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57888›,hostnossl,user=root] 3585 ={"Timestamp":1657696916033038000,"EventType":"query_execute","Statement":"‹UPDATE \"\".\"\".server_components SET name = $1, vendor = $2, model = $3, serial = $4, server_component_type_id = $5, server_id = $6, updated_at = $7 WHERE id = $8›","Tag":"UPDATE","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹''›","‹'test-5'›","‹'Right'›","‹'42d0fc33-e4c2-4e7c-8e55-911ca112ea71'›","‹'539d6c85-2344-4bbc-b62c-79ecc8f3ce2b'›","‹'2022-07-13 07:21:56.025237+00:00'›","‹'3314c271-acda-457a-961f-5e11480948b4'›"],"ExecMode":"exec","NumRows":1,"Age":3.8902,"TxnCounter":22}
I220713 07:21:56.059760 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3588 ={"Timestamp":1657696916057644100,"EventType":"query_execute","Statement":"‹SELECT count(*) FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3))›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-5'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":2.195,"FullTableScan":true,"TxnCounter":85}
I220713 07:21:56.065773 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3589 ={"Timestamp":1657696916063329800,"EventType":"query_execute","Statement":"‹SELECT * FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3)) ORDER BY server_components.created_at DESC LIMIT 100›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-5'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":2.5364,"FullTableScan":true,"TxnCounter":86}
I220713 07:21:56.097542 12489922 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57888›,hostnossl,user=root] 3595 ={"Timestamp":1657696916094798500,"EventType":"query_execute","Statement":"‹UPDATE \"\".\"\".server_components SET name = $1, vendor = $2, model = $3, serial = $4, server_component_type_id = $5, server_id = $6, updated_at = $7 WHERE id = $8›","Tag":"UPDATE","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹''›","‹'test-6'›","‹'Right'›","‹'42d0fc33-e4c2-4e7c-8e55-911ca112ea71'›","‹'539d6c85-2344-4bbc-b62c-79ecc8f3ce2b'›","‹'2022-07-13 07:21:56.087454+00:00'›","‹'3314c271-acda-457a-961f-5e11480948b4'›"],"ExecMode":"exec","NumRows":1,"Age":2.8332,"TxnCounter":26}
I220713 07:21:56.123277 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3598 ={"Timestamp":1657696916120473700,"EventType":"query_execute","Statement":"‹SELECT count(*) FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3))›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-6'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":2.8855,"FullTableScan":true,"TxnCounter":92}
I220713 07:21:56.130017 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3599 ={"Timestamp":1657696916127289300,"EventType":"query_execute","Statement":"‹SELECT * FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3)) ORDER BY server_components.created_at DESC LIMIT 100›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-6'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":2.9743,"FullTableScan":true,"TxnCounter":93}
I220713 07:21:56.159947 12489922 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57888›,hostnossl,user=root] 3605 ={"Timestamp":1657696916156940300,"EventType":"query_execute","Statement":"‹UPDATE \"\".\"\".server_components SET name = $1, vendor = $2, model = $3, serial = $4, server_component_type_id = $5, server_id = $6, updated_at = $7 WHERE id = $8›","Tag":"UPDATE","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹''›","‹'test-7'›","‹'Right'›","‹'42d0fc33-e4c2-4e7c-8e55-911ca112ea71'›","‹'539d6c85-2344-4bbc-b62c-79ecc8f3ce2b'›","‹'2022-07-13 07:21:56.149524+00:00'›","‹'3314c271-acda-457a-961f-5e11480948b4'›"],"ExecMode":"exec","NumRows":1,"Age":3.0905,"TxnCounter":30}
I220713 07:21:56.185678 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3608 ={"Timestamp":1657696916182469600,"EventType":"query_execute","Statement":"‹SELECT count(*) FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3))›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-7'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":3.3767,"FullTableScan":true,"TxnCounter":99}
I220713 07:21:56.192326 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3609 ={"Timestamp":1657696916189444100,"EventType":"query_execute","Statement":"‹SELECT * FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3)) ORDER BY server_components.created_at DESC LIMIT 100›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-7'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":2.9767,"FullTableScan":true,"TxnCounter":100}
I220713 07:21:56.219491 12489922 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57888›,hostnossl,user=root] 3615 ={"Timestamp":1657696916216535600,"EventType":"query_execute","Statement":"‹UPDATE \"\".\"\".server_components SET name = $1, vendor = $2, model = $3, serial = $4, server_component_type_id = $5, server_id = $6, updated_at = $7 WHERE id = $8›","Tag":"UPDATE","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹''›","‹'test-8'›","‹'Right'›","‹'42d0fc33-e4c2-4e7c-8e55-911ca112ea71'›","‹'539d6c85-2344-4bbc-b62c-79ecc8f3ce2b'›","‹'2022-07-13 07:21:56.208857+00:00'›","‹'3314c271-acda-457a-961f-5e11480948b4'›"],"ExecMode":"exec","NumRows":1,"Age":3.0426,"TxnCounter":34}
I220713 07:21:56.245130 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3618 ={"Timestamp":1657696916243097300,"EventType":"query_execute","Statement":"‹SELECT count(*) FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3))›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-8'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":2.1101,"FullTableScan":true,"TxnCounter":106}
I220713 07:21:56.250304 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3619 ={"Timestamp":1657696916248289900,"EventType":"query_execute","Statement":"‹SELECT * FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3)) ORDER BY server_components.created_at DESC LIMIT 100›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-8'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":2.161,"FullTableScan":true,"TxnCounter":107}
I220713 07:21:56.295140 12489922 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57888›,hostnossl,user=root] 3625 ={"Timestamp":1657696916291831800,"EventType":"query_execute","Statement":"‹UPDATE \"\".\"\".server_components SET name = $1, vendor = $2, model = $3, serial = $4, server_component_type_id = $5, server_id = $6, updated_at = $7 WHERE id = $8›","Tag":"UPDATE","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹''›","‹'test-9'›","‹'Right'›","‹'42d0fc33-e4c2-4e7c-8e55-911ca112ea71'›","‹'539d6c85-2344-4bbc-b62c-79ecc8f3ce2b'›","‹'2022-07-13 07:21:56.282897+00:00'›","‹'3314c271-acda-457a-961f-5e11480948b4'›"],"ExecMode":"exec","NumRows":1,"Age":3.3575,"TxnCounter":38}
I220713 07:21:56.320503 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3628 ={"Timestamp":1657696916316995600,"EventType":"query_execute","Statement":"‹SELECT count(*) FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3))›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-9'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":3.5888,"FullTableScan":true,"TxnCounter":113}
I220713 07:21:56.328491 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3629 ={"Timestamp":1657696916326386100,"EventType":"query_execute","Statement":"‹SELECT * FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3)) ORDER BY server_components.created_at DESC LIMIT 100›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-9'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":2.1897,"FullTableScan":true,"TxnCounter":114}
I220713 07:21:56.368319 12489922 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57888›,hostnossl,user=root] 3635 ={"Timestamp":1657696916365564300,"EventType":"query_execute","Statement":"‹UPDATE \"\".\"\".server_components SET name = $1, vendor = $2, model = $3, serial = $4, server_component_type_id = $5, server_id = $6, updated_at = $7 WHERE id = $8›","Tag":"UPDATE","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹''›","‹'test-10'›","‹'Right'›","‹'42d0fc33-e4c2-4e7c-8e55-911ca112ea71'›","‹'539d6c85-2344-4bbc-b62c-79ecc8f3ce2b'›","‹'2022-07-13 07:21:56.357923+00:00'›","‹'3314c271-acda-457a-961f-5e11480948b4'›"],"ExecMode":"exec","NumRows":1,"Age":2.8742,"TxnCounter":42}
I220713 07:21:56.395537 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3638 ={"Timestamp":1657696916393215600,"EventType":"query_execute","Statement":"‹SELECT count(*) FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3))›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-10'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":2.4695,"FullTableScan":true,"TxnCounter":120}
I220713 07:21:56.402186 12489907 9@util/log/event_log.go:32 ⋮ [n1,client=‹172.22.0.1:57886›,hostnossl,user=root] 3639 ={"Timestamp":1657696916399287300,"EventType":"query_execute","Statement":"‹SELECT * FROM \"\".\"\".server_components WHERE (((server_components.name = $1) AND (server_components.model = $2)) AND (server_components.serial = $3)) ORDER BY server_components.created_at DESC LIMIT 100›","Tag":"SELECT","User":"root","PlaceholderValues":["‹'Normal Fin'›","‹'test-10'›","‹'Right'›"],"ExecMode":"exec","NumRows":1,"Age":2.954,"FullTableScan":true,"TxnCounter":121}

### PR DESCRIPTION
**Pull request by joelrebel**
This resolves #105 where the test case made some assumptions about the fixtures and failed
intermittently.

The change fixes up the `TestIntegrationServerUpdateComponents` test case method to work with components that are present in the fixture data. The earlier revision of this test assumed the first element in the servers, components list is the expected fixture it needs to work with, which is not often the case, since servers, components can be returned in a random order and so the test would fail intermittently.

### CODE REVIEW

**Comment by JAORMX** [comment]
@joelrebel could you re-visit the PR description to give more descriptive detail about what's being changed? This only explains the "why".

File: pkg/api/v1/router_server_components_test.go [hunk 1]
```diff
@@ -517,17 +517,41 @@ func TestIntegrationServerUpdateComponents(t *testing.T) {
...
+	var serverFixture serverservice.Server
+
+	// The component fixture targeted in test cases below
+	fixtureComponentName := "My Lucky Fin"
+	fixtureComponentVendor := "Barracuda"
+	fixtureComponentSerial := "Right"
+
+	// identify component and server fixture for test
+	for _, server := range servers {
+		server := server
```
Comment (JAORMX) [inline pkg/api/v1/router_server_components_test.go:532]: why do you copy the value that's already copied by the for loop? Do you need the copied value or do you need a reference to the item in the list?

File: pkg/api/v1/router_server_components_test.go [hunk 2]
```diff
@@ -517,17 +517,41 @@ func TestIntegrationServerUpdateComponents(t *testing.T) {
...
+		for _, c := range server.Components {
```
Comment (JAORMX) [inline pkg/api/v1/router_server_components_test.go:533]: same question here with the component. In this case, it's better to iterate the id's... e.g.:

```
for idx := range server.Components {
```

and then copy set the memory reference in a variable.

**Review by JAORMX — CHANGES_REQUESTED** [review]

File: pkg/api/v1/router_server_components_test.go (hunk 1 above)
Comment (joelrebel) [reply pkg/api/v1/router_server_components_test.go]: @JAORMX In this case we're keeping a copy of the server component, and so the `server := server` copy is unnecessary - most likely left over from a previous change, fixed in 81e7ea5.

File: pkg/api/v1/router_server_components_test.go (hunk 2 above)
Comment (joelrebel) [reply pkg/api/v1/router_server_components_test.go:532]: I think the `c := c` was from a previous change in the code where the object was being stored as a pointer in a slice, where I was being cautious about the common range temporary variable gotcha, that along with trying not to type as much to reference each of the struct fields - `c.Name == fixtureComponentName`. 

Thanks for pointing it out, I've pushed a fix https://github.com/metal-toolbox/hollow-serverservice/pull/118/commits/81e7ea5e64883b10fc46374399ed56831c94c70f to remove the range variable copying which isn't necessary since the component objects are being stored by value.

**Review by JAORMX — APPROVED** [review]

**Comment by joelrebel** [comment]
force pushed with signed commits

**Review by JAORMX — APPROVED** [review]
